### ISSUE TITLE
Implement at least one variant of ZKP Socialist Millionaire Protocol authentication protocol

### ISSUE THREAD

**Issue by arijitdasgupta** [getonchain/yudhisthira#4]
Dev notes:
 - https://shanetully.com/2013/08/mitm-protection-via-the-socialist-millionaire-protocol-otr-style/

**Comment by RatulSaha** [comment]
https://github.com/getonchain/yudhisthira/commit/0da3d891a16ae758e3538598b8194f5f5d785ec9.
